# Generated by Django 6.0.7 on 2026-08-24 21:57

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount_user'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='عام', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_books', to='account.useraccount'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, validators=[books.validators.validate_book_title]),
        ),
    ]
